import os
import json
from pathlib import Path
from rich.console import Console
from github import Github
import git
from dotenv import load_dotenv

load_dotenv()


def apply_diffs():
    """Apply the generated diffs to the actual files using GitPython."""
    diff_log_path = Path("logs/diffs.log")

    if not diff_log_path.exists():
        raise FileNotFoundError("No diffs.log found. Run 5_create_diffs.py first.")

    console = Console()

    # Check if there are any diffs to apply
    if diff_log_path.stat().st_size == 0:
        console.print("✅ No diffs to apply, skipping.")
        return

    repo = git.Repo(".")

    # Apply diffs using GitPython by passing the file path directly
    try:
        # Pass the patch file directly to git apply
        repo.git.apply("--verbose", str(diff_log_path))
        console.print("✅ Diffs applied successfully")

    except git.exc.GitCommandError as e:
        raise RuntimeError(f"Failed to apply diffs: {e}")


def create_pr(title: str, body: str, branch_name: str = "docweaver-updates"):
    """Create a PR with the applied changes using PyGithub."""
    console = Console()

    # Get GitHub token from environment
    github_token = os.getenv("GITHUB_TOKEN")
    if not github_token:
        raise ValueError("GITHUB_TOKEN environment variable not set")

    # Initialize Git and GitHub clients
    repo = git.Repo(".")
    g = Github(github_token)

    # Get remote URLs to determine fork and upstream
    origin_url = repo.remotes.origin.url
    fork_owner = origin_url.split("/")[-2].split(":")[-1]  # Extract owner from URL
    repo_name = origin_url.split("/")[-1].replace(".git", "")

    # Create and checkout new branch
    if branch_name in repo.heads:
        console.print(f"Branch '{branch_name}' already exists. Recreating it.")
        repo.delete_head(branch_name, force=True)

    new_branch = repo.create_head(branch_name)
    new_branch.checkout()

    # Stage and commit changes
    repo.git.add(".")
    repo.index.commit(title)

    # Push to fork
    repo.remotes.origin.push(new_branch)

    # Create PR using PyGithub
    github_repo = g.get_repo(f"{fork_owner}/{repo_name}")

    # Assume upstream is "weaviate/weaviate-io" - adjust as needed
    upstream_repo = g.get_repo("databyjp/docs")

    pr = upstream_repo.create_pull(
        title=title, body=body, head=f"{fork_owner}:{branch_name}", base="main"
    )

    console.print(f"✅ PR created: {pr.html_url}")
    return pr


def main():
    console = Console()

    try:
        console.print("📝 Applying diffs...")
        apply_diffs()

        console.print("🚀 Creating PR...")
        create_pr(
            title="📚 Automated documentation updates via DocWeaver",
            body="This PR contains automated documentation improvements generated by DocWeaver.\n\n"
            "Changes include content updates, formatting improvements, and clarity enhancements.",
        )

    except Exception as e:
        console.print(f"❌ Error: {e}")


if __name__ == "__main__":
    main()
